/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Silverbullet Backend API
 * Comprehensive API reference for the Silverbullet backend, generated from JSDoc @swagger annotations and Express route introspection.
 * OpenAPI spec version: 1.0.0
 */
import zod from 'zod';

/**
 * Valid role ints: 0=Owner, 1=Co-Owner, 2=Moderator, 3=Support. Assigning 0 requires requester to be Owner.
 * @summary Apply admin role bitmap to a batch of ADMIN users.
 */
export const postApiAdminUsersAdminRolesBody = zod.object({
  "usernames": zod.array(zod.string()),
  "roles": zod.array(zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3)])).optional()
})


/**
 * @summary Create a new ADMIN account (seeded with credits and red name color).
 */
export const postApiAdminCreateAdminBodyPasswordMin = 12;

export const postApiAdminCreateAdminBody = zod.object({
  "username": zod.string(),
  "email": zod.email(),
  "password": zod.string().min(postApiAdminCreateAdminBodyPasswordMin).describe('Must include upper')
})


/**
 * Admin-only. Accepts multipart/form-data with a config file, title, and description.
 * @summary Upload an admin config (.espk) file.
 */
export const postApiAdminUploadConfigBody = zod.object({
  "file": zod.instanceof(File).optional(),
  "title": zod.string().optional(),
  "description": zod.string().optional()
})


/**
 * All sensitive fields are RSA-encrypted client-side using the key from /auth/publicKey. Protected by Cloudflare Turnstile.
 * @summary Register a new user account.
 */
export const postApiAuthRegisterBody = zod.object({
  "encryptedUsername": zod.string().describe('Base64 RSA-encrypted username.'),
  "encryptedEmail": zod.string().describe('Base64 RSA-encrypted email.'),
  "encryptedPassword": zod.string().describe('Base64 RSA-encrypted password.'),
  "hCaptchaToken": zod.string().describe('hCaptcha token.')
})


/**
 * @summary Log in with an encrypted email and password.
 */
export const postApiAuthLoginBody = zod.object({
  "encryptedEmail": zod.string(),
  "encryptedPassword": zod.string(),
  "hCaptchaToken": zod.string()
})


/**
 * @summary Queue a password recovery request for the given email.
 */
export const postApiAuthRecoveryBody = zod.object({
  "encryptedEmail": zod.string(),
  "hCaptchaToken": zod.string()
})


/**
 * @summary Reset password using recovery token.
 */
export const postApiAuthResetPasswordBody = zod.object({
  "token": zod.string(),
  "encryptedPassword": zod.string(),
  "hCaptchaToken": zod.string()
})


/**
 * @summary Public contact transmission forwarded to admin Telegram.
 */
export const postApiContactBodySubjectMax = 200;export const postApiContactBodyMessageMax = 5000;

export const postApiContactBody = zod.object({
  "email": zod.email(),
  "subject": zod.string().max(postApiContactBodySubjectMax).optional(),
  "message": zod.string().max(postApiContactBodyMessageMax)
})


/**
 * @summary Change the authenticated user's username (costs 200 BLT unless admin).
 */
export const postApiUserChangeUsernameBody = zod.object({
  "newUsername": zod.string()
})


/**
 * @summary Change the authenticated user's password.
 */
export const postApiUserChangePasswordBodyNewPasswordMin = 6;

export const postApiUserChangePasswordBody = zod.object({
  "oldPassword": zod.string(),
  "newPassword": zod.string().min(postApiUserChangePasswordBodyNewPasswordMin)
})


/**
 * @summary Upload a new avatar image (multipart).
 */
export const postApiUserAvatarBody = zod.object({
  "file": zod.instanceof(File).optional()
})


/**
 * @summary Set or clear the avatar URL (must be http/https).
 */
export const postApiUserAvatarUrlBody = zod.object({
  "avatarUrl": zod.url().nullish()
})


/**
 * @summary Toggle a profile endorsement/like for another user.
 */
export const postApiUserLikeBody = zod.object({
  "targetUsername": zod.string()
})


/**
 * @summary Update the caller's short biography (max 120 chars).
 */
export const postApiUserBioBodyBioMax = 120;

export const postApiUserBioBody = zod.object({
  "bio": zod.string().max(postApiUserBioBodyBioMax)
})


/**
 * @summary Purchase a cosmetic (verified badge or 30-day color/effect pass).
 */
export const postApiUserBuyCosmeticBody = zod.object({
  "type": zod.enum(['badge', 'color_pass']),
  "hexColor": zod.string().optional().describe('Required for color_pass; must match /^#[0-9A-Fa-f]{6}$/.'),
  "effect": zod.string().optional().describe('Optional display effect for color_pass.')
})


/**
 * @summary Submit a new support ticket.
 */
export const postApiSupportTicketBody = zod.object({
  "subject": zod.string(),
  "message": zod.string()
})


/**
 * @summary Create a pending crypto deposit invoice.
 */
export const postApiCryptoInvoiceBody = zod.object({
  "amountUsd": zod.number().min(1)
})


/**
 * Supported itemType values: RANK_STARTER, RANK_PRO, RANK_PREMIUM, RANK_ENTERPRISE,
SOFTWARE_ONLY, SUB_BLUE_BADGE, SUB_COSMETICS. Vendor ranks require a shopName.

 * @summary Purchase a platform upgrade with BLT credits.
 */
export const postApiPlatformBuyUpgradeBody = zod.object({
  "itemType": zod.enum(['RANK_STARTER', 'RANK_PRO', 'RANK_PREMIUM', 'RANK_ENTERPRISE', 'SOFTWARE_ONLY', 'SUB_BLUE_BADGE', 'SUB_COSMETICS']),
  "shopName": zod.string().optional()
})


/**
 * @summary Buy a single unit of a product (legacy endpoint using product stock counter).
 */
export const postApiMarketplaceBuyBody = zod.object({
  "productId": zod.string()
})


/**
 * @summary Create a market ticket against a shop.
 */
export const postApiTicketsCreateBody = zod.object({
  "shopId": zod.string(),
  "message": zod.string()
})


/**
 * @summary Place a 24h marketplace visibility bid for your shop.
 */
export const postApiEnterpriseBidBodyAmountMin = 0.01;

export const postApiEnterpriseBidBody = zod.object({
  "amount": zod.number().min(postApiEnterpriseBidBodyAmountMin)
})


/**
 * @summary Create the vendor's first storefront (requires vendor rank and Telegram link).
 */
export const postApiEnterpriseSetupBodyShopNameMax = 30;

export const postApiEnterpriseSetupBody = zod.object({
  "shopName": zod.string().max(postApiEnterpriseSetupBodyShopNameMax),
  "avatarUrl": zod.string().optional(),
  "bannerUrl": zod.string().optional()
})


/**
 * @summary Bulk update price for all products in a category owned by the caller.
 */
export const putApiEnterpriseBulkPriceBody = zod.object({
  "category": zod.string(),
  "newPrice": zod.number().min(1)
})


/**
 * Each non-empty line of logContent becomes a separate single-stock product entry.
 * @summary Create multiple products from a multi-line log payload.
 */
export const postApiEnterpriseProductsBody = zod.object({
  "productName": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number().min(1),
  "logContent": zod.string().describe('Newline-separated log entries.'),
  "category": zod.string().optional(),
  "country": zod.string().optional()
})


/**
 * @summary Purchase a shop cosmetic (verified badge / color pass / avatar+info update).
 */
export const postApiEnterpriseBuyCosmeticBody = zod.object({
  "type": zod.enum(['badge', 'color_pass', 'avatar_update']),
  "hexColor": zod.string().optional(),
  "effect": zod.string().optional(),
  "avatarUrl": zod.string().optional(),
  "bannerUrl": zod.string().optional(),
  "shopName": zod.string().optional(),
  "shopDescription": zod.string().optional()
})


/**
 * @summary Request a crypto withdrawal from the vendor vault (min $50).
 */
export const postApiEnterpriseWithdrawBodyAmountMin = 50;

export const postApiEnterpriseWithdrawBody = zod.object({
  "cryptoAddress": zod.string(),
  "network": zod.string(),
  "amount": zod.number().min(postApiEnterpriseWithdrawBodyAmountMin)
})


/**
 * @summary Bulk delete all products in a given category owned by the caller.
 */
export const deleteApiEnterpriseBulkProductsBody = zod.object({
  "category": zod.string()
})


/**
 * @summary Granular bulk actions for specific product IDs.
 */
export const postApiEnterpriseBulkActionsBody = zod.object({
  "action": zod.enum(['DELETE', 'UPDATE_PRICE']),
  "productIds": zod.array(zod.string()),
  "newPrice": zod.number().optional()
})


/**
 * @summary Open a dispute on an order (5 minute window).
 */
export const postApiOrdersDisputeBody = zod.object({
  "orderId": zod.string(),
  "target": zod.enum(['ADMIN', 'VENDOR'])
})


/**
 * @summary Vendor supplies a replacement log for an active dispute.
 */
export const postApiVendorReplaceLogBody = zod.object({
  "disputeId": zod.string(),
  "replacementLog": zod.string()
})


/**
 * @summary Purchase an ad slot with BLT credits.
 */
export const postApiAdsPurchaseBodySlotIdMax = 6;

export const postApiAdsPurchaseBody = zod.object({
  "slotId": zod.number().min(1).max(postApiAdsPurchaseBodySlotIdMax),
  "durationDays": zod.union([zod.literal(14),zod.literal(30)]),
  "imageUrl": zod.string(),
  "targetUrl": zod.string()
})


/**
 * @summary Submit a new custom tool request for admin approval.
 */
export const postApiRequestsSubmitBodyTitleMax = 150;export const postApiRequestsSubmitBodyDescriptionMax = 5000;

export const postApiRequestsSubmitBody = zod.object({
  "title": zod.string().max(postApiRequestsSubmitBodyTitleMax),
  "description": zod.string().max(postApiRequestsSubmitBodyDescriptionMax)
})


/**
 * @summary Open a formal dispute on an order with an initial message (5 minute window).
 */
export const postApiMarketDisputeReportBody = zod.object({
  "orderId": zod.string(),
  "initialMessage": zod.string()
})


/**
 * @summary Rate a config from 1 to 5 (daily limits by rank).
 */
export const postApiConfigsIdRateBodyScoreMax = 5;

export const postApiConfigsIdRateBody = zod.object({
  "score": zod.number().min(1).max(postApiConfigsIdRateBodyScoreMax)
})


/**
 * @summary Post a reply in an open dispute thread.
 */
export const postApiMarketDisputeOrderIdReplyBody = zod.object({
  "message": zod.string()
})


/**
 * @summary Admin-only arbitration that approves or rejects the refund.
 */
export const postApiMarketDisputeOrderIdResolveBody = zod.object({
  "action": zod.enum(['APPROVE', 'REJECT'])
})


/**
 * @summary Update an unsold product owned by the vendor.
 */
export const putApiEnterpriseProductsIdBody = zod.object({
  "productName": zod.string(),
  "country": zod.string(),
  "logContent": zod.string(),
  "price": zod.number().min(1)
})


/**
 * @summary Purchase N stock lines from a product (preferred over /marketplace/buy).
 */
export const postApiMarketPurchaseProductIdBodyAmountDefault = 1;

export const postApiMarketPurchaseProductIdBody = zod.object({
  "amount": zod.number().min(1).default(postApiMarketPurchaseProductIdBodyAmountDefault)
})


/**
 * @summary Submit a one-time review for a purchased order.
 */
export const postApiMarketReviewProductIdBodyScoreMax = 5;

export const postApiMarketReviewProductIdBody = zod.object({
  "score": zod.number().min(1).max(postApiMarketReviewProductIdBodyScoreMax),
  "orderId": zod.string()
})


/**
 * @summary Purchase N stock lines of a product and decrypt the payload.
 */
export const postApiMarketplaceBuyProductIdBodyAmountDefault = 1;

export const postApiMarketplaceBuyProductIdBody = zod.object({
  "amount": zod.number().min(1).default(postApiMarketplaceBuyProductIdBodyAmountDefault)
})


/**
 * @summary Credit BLT to a user's balance (audited).
 */
export const postApiAdminUsersUsernameCreditsAddBody = zod.object({
  "amount": zod.number().min(1)
})


/**
 * @summary Debit BLT from a user's balance (audited).
 */
export const postApiAdminUsersUsernameCreditsReduceBody = zod.object({
  "amount": zod.number().min(1)
})


/**
 * @summary Change a user's rank. Granting ADMIN requires Owner role.
 */
export const postApiAdminUsersUsernameRankBody = zod.object({
  "rank": zod.enum(['USER', 'STARTER', 'PRO', 'PREMIUM', 'ENTERPRISE', 'ADMIN'])
})


/**
 * @summary Set a custom vendor split (0.00-1.00) or clear it.
 */
export const postApiAdminUsersUsernameSplitBodySplitMinOne = 0;
export const postApiAdminUsersUsernameSplitBodySplitMaxOne = 1;

export const postApiAdminUsersUsernameSplitBody = zod.object({
  "split": zod.union([zod.number().min(postApiAdminUsersUsernameSplitBodySplitMinOne).max(postApiAdminUsersUsernameSplitBodySplitMaxOne),zod.enum(['clear']),zod.null()]).optional()
})


/**
 * Changing another admin's password requires Owner role.
 * @summary Administratively reset a user's password.
 */
export const postApiAdminUsersUsernamePasswordBodyNewPasswordMin = 12;

export const postApiAdminUsersUsernamePasswordBody = zod.object({
  "newPassword": zod.string().min(postApiAdminUsersUsernamePasswordBodyNewPasswordMin)
})


/**
 * @summary Update a user's email address.
 */
export const postApiAdminUsersUsernameEmailBody = zod.object({
  "newEmail": zod.email()
})


/**
 * @summary Rename a user account.
 */
export const postApiAdminUsersUsernameRenameBodyNewUsernameMin = 3;

export const postApiAdminUsersUsernameRenameBody = zod.object({
  "newUsername": zod.string().min(postApiAdminUsersUsernameRenameBodyNewUsernameMin)
})


/**
 * @summary Ban a non-admin user for N days with a reason.
 */
export const postApiAdminUsersUsernameBanBody = zod.object({
  "days": zod.number().min(1),
  "reason": zod.string()
})


/**
 * @summary Toggle a badge or clear all badges for a user.
 */
export const postApiAdminUsersUsernameBadgesBody = zod.object({
  "badge": zod.enum(['DEV', 'LGBTQ', 'BUG_HUNTER', 'GHOST']).optional(),
  "action": zod.enum(['toggle', 'clear']).optional()
})


/**
 * @summary Resolve a dispute from the admin panel by approving or rejecting refund.
 */
export const postApiAdminDisputesOrderIdResolveBody = zod.object({
  "action": zod.enum(['APPROVE', 'REJECT'])
})


/**
 * @summary Reply to a support ticket as admin and notify the user.
 */
export const postApiAdminTicketsIdReplyBody = zod.object({
  "message": zod.string()
})
